[theme]
primaryColor = "#d64545"              # Vermelho suave (impactante, mas elegante)
backgroundColor = "#fdfaf6"           # Bege claro e neutro
secondaryBackgroundColor = "#f3f4f6"  # Branco gelo (ótimo para containers)
textColor = "#2d2d2d"                 # Grafite escuro
font = "sans serif"
